[core]
# Load after omni.usd.libs (-1000) and before omni.usd (0)
# See https://docs.omniverse.nvidia.com/py/kit/docs/guide/usd_schema.html
order = -100

[package]
version = "0.0.0"
category = "simulation"
feature = false
app = false
title = "Cesium for Omniverse"
description = "High-accuracy full-scale WGS84 globe for Omniverse"
authors = "Cesium GS Inc."
repository = "https://github.com/CesiumGS/cesium-omniverse"
keywords = [
    "cesium",
    "omniverse",
    "geospatial",
    "3D Tiles",
    "glTF",
    "globe",
    "earth",
    "simulation",
]

# Paths are relative to the extension folder
changelog = "doc/CHANGES.md"
readme = "doc/README.md"
preview_image = "doc/images/preview.jpg"
icon = "doc/images/icon.png"

# Which extensions this extension depends on
[dependencies]
# usdrt.scenegraph depends on omni.usd.libs
"usdrt.scenegraph" = {}
"omni.kit.uiapp" = {}
"omni.kit.viewport.utility" = {}

# Main python module this extension provides, it will be publicly available as "import cesium.omniverse"
[[python.module]]
name = "cesium.omniverse"

[[native.library]]
path = "bin/${lib_prefix}InMemoryAssetResolver${lib_ext}"

[[native.library]]
path = "bin/${lib_prefix}CesiumOmniverse${lib_ext}"
