// GENERATED FILE.  DO NOT EDIT.
#include "pxr/external/boost/python/class.hpp"
#include ".//tokens.h"

PXR_NAMESPACE_USING_DIRECTIVE

#define _ADD_TOKEN(cls, name) \
    cls.add_static_property(#name, +[]() { return CesiumTokens->name.GetString(); });

void wrapCesiumTokens()
{
    pxr_boost::python::class_<CesiumTokensType, pxr_boost::python::noncopyable>
        cls("Tokens", pxr_boost::python::no_init);
    _ADD_TOKEN(cls, cesiumAlpha);
    _ADD_TOKEN(cls, cesiumAnchorAdjustOrientationForGlobeWhenMoving);
    _ADD_TOKEN(cls, cesiumAnchorDetectTransformChanges);
    _ADD_TOKEN(cls, cesiumAnchorGeoreferenceBinding);
    _ADD_TOKEN(cls, cesiumAnchorHeight);
    _ADD_TOKEN(cls, cesiumAnchorLatitude);
    _ADD_TOKEN(cls, cesiumAnchorLongitude);
    _ADD_TOKEN(cls, cesiumAnchorPosition);
    _ADD_TOKEN(cls, cesiumBaseUrl);
    _ADD_TOKEN(cls, cesiumCartographicPolygonBinding);
    _ADD_TOKEN(cls, cesiumCulledScreenSpaceError);
    _ADD_TOKEN(cls, cesiumDebugDisableGeometryPool);
    _ADD_TOKEN(cls, cesiumDebugDisableGeoreferencing);
    _ADD_TOKEN(cls, cesiumDebugDisableMaterialPool);
    _ADD_TOKEN(cls, cesiumDebugDisableMaterials);
    _ADD_TOKEN(cls, cesiumDebugDisableTexturePool);
    _ADD_TOKEN(cls, cesiumDebugDisableTextures);
    _ADD_TOKEN(cls, cesiumDebugGeometryPoolInitialCapacity);
    _ADD_TOKEN(cls, cesiumDebugMaterialPoolInitialCapacity);
    _ADD_TOKEN(cls, cesiumDebugRandomColors);
    _ADD_TOKEN(cls, cesiumDebugTexturePoolInitialCapacity);
    _ADD_TOKEN(cls, cesiumDisplayName);
    _ADD_TOKEN(cls, cesiumEast);
    _ADD_TOKEN(cls, cesiumEcefToUsdTransform);
    _ADD_TOKEN(cls, cesiumEllipsoidBinding);
    _ADD_TOKEN(cls, cesiumEnableFogCulling);
    _ADD_TOKEN(cls, cesiumEnableFrustumCulling);
    _ADD_TOKEN(cls, cesiumEnforceCulledScreenSpaceError);
    _ADD_TOKEN(cls, cesiumExcludeSelectedTiles);
    _ADD_TOKEN(cls, cesiumForbidHoles);
    _ADD_TOKEN(cls, cesiumFormat);
    _ADD_TOKEN(cls, cesiumGeoreferenceBinding);
    _ADD_TOKEN(cls, cesiumGeoreferenceOriginHeight);
    _ADD_TOKEN(cls, cesiumGeoreferenceOriginLatitude);
    _ADD_TOKEN(cls, cesiumGeoreferenceOriginLongitude);
    _ADD_TOKEN(cls, cesiumInvertSelection);
    _ADD_TOKEN(cls, cesiumIonAccessToken);
    _ADD_TOKEN(cls, cesiumIonAssetId);
    _ADD_TOKEN(cls, cesiumIonServerApiUrl);
    _ADD_TOKEN(cls, cesiumIonServerApplicationId);
    _ADD_TOKEN(cls, cesiumIonServerBinding);
    _ADD_TOKEN(cls, cesiumIonServerUrl);
    _ADD_TOKEN(cls, cesiumLayer);
    _ADD_TOKEN(cls, cesiumLayers);
    _ADD_TOKEN(cls, cesiumLoadingDescendantLimit);
    _ADD_TOKEN(cls, cesiumMainThreadLoadingTimeLimit);
    _ADD_TOKEN(cls, cesiumMaximumCachedBytes);
    _ADD_TOKEN(cls, cesiumMaximumLevel);
    _ADD_TOKEN(cls, cesiumMaximumScreenSpaceError);
    _ADD_TOKEN(cls, cesiumMaximumSimultaneousTileLoads);
    _ADD_TOKEN(cls, cesiumMaximumTextureSize);
    _ADD_TOKEN(cls, cesiumMaximumZoomLevel);
    _ADD_TOKEN(cls, cesiumMinimumLevel);
    _ADD_TOKEN(cls, cesiumMinimumZoomLevel);
    _ADD_TOKEN(cls, cesiumNorth);
    _ADD_TOKEN(cls, cesiumOverlayRenderMethod);
    _ADD_TOKEN(cls, cesiumPointSize);
    _ADD_TOKEN(cls, cesiumPreloadAncestors);
    _ADD_TOKEN(cls, cesiumPreloadSiblings);
    _ADD_TOKEN(cls, cesiumProjectDefaultIonAccessToken);
    _ADD_TOKEN(cls, cesiumProjectDefaultIonAccessTokenId);
    _ADD_TOKEN(cls, cesiumRadii);
    _ADD_TOKEN(cls, cesiumRasterOverlayBinding);
    _ADD_TOKEN(cls, cesiumRootTilesX);
    _ADD_TOKEN(cls, cesiumRootTilesY);
    _ADD_TOKEN(cls, cesiumSelectedIonServer);
    _ADD_TOKEN(cls, cesiumShowCreditsOnScreen);
    _ADD_TOKEN(cls, cesiumSmoothNormals);
    _ADD_TOKEN(cls, cesiumSourceType);
    _ADD_TOKEN(cls, cesiumSouth);
    _ADD_TOKEN(cls, cesiumSpecifyTileMatrixSetLabels);
    _ADD_TOKEN(cls, cesiumSpecifyTilingScheme);
    _ADD_TOKEN(cls, cesiumSpecifyZoomLevels);
    _ADD_TOKEN(cls, cesiumStyle);
    _ADD_TOKEN(cls, cesiumSubTileCacheBytes);
    _ADD_TOKEN(cls, cesiumSuspendUpdate);
    _ADD_TOKEN(cls, cesiumTileHeight);
    _ADD_TOKEN(cls, cesiumTileMatrixSetId);
    _ADD_TOKEN(cls, cesiumTileMatrixSetLabelPrefix);
    _ADD_TOKEN(cls, cesiumTileMatrixSetLabels);
    _ADD_TOKEN(cls, cesiumTileWidth);
    _ADD_TOKEN(cls, cesiumUrl);
    _ADD_TOKEN(cls, cesiumUseWebMercatorProjection);
    _ADD_TOKEN(cls, cesiumWest);
    _ADD_TOKEN(cls, clip);
    _ADD_TOKEN(cls, ion);
    _ADD_TOKEN(cls, overlay);
    _ADD_TOKEN(cls, url);
    _ADD_TOKEN(cls, CesiumDataPrim);
    _ADD_TOKEN(cls, CesiumEllipsoidPrim);
    _ADD_TOKEN(cls, CesiumGeoreferencePrim);
    _ADD_TOKEN(cls, CesiumGlobeAnchorSchemaAPI);
    _ADD_TOKEN(cls, CesiumIonRasterOverlayPrim);
    _ADD_TOKEN(cls, CesiumIonServerPrim);
    _ADD_TOKEN(cls, CesiumPolygonRasterOverlayPrim);
    _ADD_TOKEN(cls, CesiumRasterOverlayPrim);
    _ADD_TOKEN(cls, CesiumTileMapServiceRasterOverlayPrim);
    _ADD_TOKEN(cls, CesiumTilesetPrim);
    _ADD_TOKEN(cls, CesiumWebMapServiceRasterOverlayPrim);
    _ADD_TOKEN(cls, CesiumWebMapTileServiceRasterOverlayPrim);
}
