from typing import Any, ClassVar

import Boost.Python
import pxr.Usd

__MFB_FULL_PACKAGE_NAME: str

class Data(pxr.Usd.Typed):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def CreateGeoreferenceOriginHeightAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateGeoreferenceOriginLatitudeAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateGeoreferenceOriginLongitudeAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateProjectDefaultIonAccessTokenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateProjectDefaultIonAccessTokenIdAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Define(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Get(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetGeoreferenceOriginHeightAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetGeoreferenceOriginLatitudeAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetGeoreferenceOriginLongitudeAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetProjectDefaultIonAccessTokenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetProjectDefaultIonAccessTokenIdAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSchemaAttributeNames(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def _GetStaticTfType(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __bool__(cls) -> bool: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class Imagery(pxr.Usd.Typed):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def CreateIonAccessTokenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateIonAssetIdAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateShowCreditsOnScreenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Define(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Get(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetIonAccessTokenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetIonAssetIdAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSchemaAttributeNames(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetShowCreditsOnScreenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def _GetStaticTfType(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __bool__(cls) -> bool: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class TilesetAPI(pxr.Usd.APISchemaBase):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def Apply(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CanApply(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateCulledScreenSpaceErrorAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateEnableFogCullingAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateEnableFrustumCullingAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateEnforceCulledScreenSpaceErrorAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateForbidHolesAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateIonAccessTokenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateIonAssetIdAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateLoadingDescendantLimitAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateMaximumCachedBytesAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateMaximumScreenSpaceErrorAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateMaximumSimultaneousTileLoadsAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreatePreloadAncestorsAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreatePreloadSiblingsAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateShowCreditsOnScreenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateSmoothNormalsAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateSourceTypeAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateSuspendUpdateAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def CreateUrlAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def Get(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetCulledScreenSpaceErrorAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEnableFogCullingAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEnableFrustumCullingAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetEnforceCulledScreenSpaceErrorAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetForbidHolesAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetIonAccessTokenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetIonAssetIdAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetLoadingDescendantLimitAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetMaximumCachedBytesAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetMaximumScreenSpaceErrorAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetMaximumSimultaneousTileLoadsAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetPreloadAncestorsAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetPreloadSiblingsAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSchemaAttributeNames(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetShowCreditsOnScreenAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSmoothNormalsAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSourceTypeAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetSuspendUpdateAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def GetUrlAttr(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def _GetStaticTfType(cls, *args, **kwargs) -> Any: ...
    @classmethod
    def __bool__(cls) -> bool: ...
    @classmethod
    def __reduce__(cls) -> Any: ...

class Tokens(Boost.Python.instance):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @property
    def cesiumCulledScreenSpaceError(self) -> Any: ...
    @property
    def cesiumEnableFogCulling(self) -> Any: ...
    @property
    def cesiumEnableFrustumCulling(self) -> Any: ...
    @property
    def cesiumEnforceCulledScreenSpaceError(self) -> Any: ...
    @property
    def cesiumForbidHoles(self) -> Any: ...
    @property
    def cesiumGeoreferenceOriginHeight(self) -> Any: ...
    @property
    def cesiumGeoreferenceOriginLatitude(self) -> Any: ...
    @property
    def cesiumGeoreferenceOriginLongitude(self) -> Any: ...
    @property
    def cesiumIonAccessToken(self) -> Any: ...
    @property
    def cesiumIonAssetId(self) -> Any: ...
    @property
    def cesiumLoadingDescendantLimit(self) -> Any: ...
    @property
    def cesiumMaximumCachedBytes(self) -> Any: ...
    @property
    def cesiumMaximumScreenSpaceError(self) -> Any: ...
    @property
    def cesiumMaximumSimultaneousTileLoads(self) -> Any: ...
    @property
    def cesiumPreloadAncestors(self) -> Any: ...
    @property
    def cesiumPreloadSiblings(self) -> Any: ...
    @property
    def cesiumProjectDefaultIonAccessToken(self) -> Any: ...
    @property
    def cesiumProjectDefaultIonAccessTokenId(self) -> Any: ...
    @property
    def cesiumShowCreditsOnScreen(self) -> Any: ...
    @property
    def cesiumSmoothNormals(self) -> Any: ...
    @property
    def cesiumSourceType(self) -> Any: ...
    @property
    def cesiumSuspendUpdate(self) -> Any: ...
    @property
    def cesiumUrl(self) -> Any: ...
    @property
    def ion(self) -> Any: ...
    @property
    def url(self) -> Any: ...

class _CanApplyResult(Boost.Python.instance):
    __instance_size__: ClassVar[int] = ...
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def __bool__(cls) -> bool: ...
    @classmethod
    def __eq__(cls, other) -> bool: ...
    @classmethod
    def __getitem__(cls, index) -> Any: ...
    @classmethod
    def __ne__(cls, other) -> bool: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @property
    def whyNot(self) -> Any: ...
