import pxr.Usd
import Boost.Python

__all__ = [
    "Data",
    "Georeference",
    "Imagery",
    "Session",
    "Tileset",
    "Tokens",
    "GlobeAnchorAPI",
]


# TODO: Fill out these stubs since we can't seem to autogen them.
class Data(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance): ...
class Georeference(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance): ...

class Imagery(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance): ...
class Session(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance): ...
class Tileset(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance): ...
class Tokens(Boost.Python.instance): ...
class GlobeAnchorAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance): ...
