[package]
version = "0.1.0"
category = "simulation"
feature = false
app = false
title = "Cesium for Omniverse Tests"
description = "An extention to run tests against Cesium for Omniverse."
authors = "Cesium GS Inc."
repository = "https://github.com/CesiumGS/cesium-omniverse"
keywords = [
    "cesium",
    "omniverse",
    "geospatial",
    "3D Tiles",
    "glTF",
    "globe",
    "earth",
    "simulation",
    "test",
]

# Paths are relative to the extension folder
readme = "doc/README.md"
preview_image = "doc/resources/icon.png"
icon = "doc/resources/icon.png"

[package.target]
kit = ["105.*"]

# Which extensions this extension depends on
[dependencies]
"cesium.usd.plugins" = {}
"usdrt.scenegraph" = {}

# Main python module this extension provides, it will be publicly available as "import cesium.omniverse"
[[python.module]]
name = "cesium.omniverse.cpp.tests"

[[native.plugin]]
path = "bin/cesium.omniverse.cpp.tests.plugin"
