[package]
title = "Cesium for Omniverse Performance Profiling Extension"
version = "0.0.0"
app = false
toggleable = false

[dependencies]
"cesium.omniverse" = {}

[[python.module]]
name = "cesium.profiling.app"
